### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by mycompassspins** [AndroidNextdoor/myFirstAngularApp#1]
Two main things:

1) The first and most crucial missing piece is that none of your routes will ever load even if they're configured correctly because you have no `<router-outlet></router-outlet>`. That is really the only thing that should be in your `app.component.html`. 

2) The main route in your app (`/`) is trying to redirect to a route that doesn't exist (`/nixdorf`). What you want is something like:

```
[
    // I know there is no HomeComponent, that's a hint to how things might be better structured
    { path: '', component: HomeComponent },
    // Again, a hint/suggestion 
    { path: 'about', component: AboutComponent },
    // Redirect all routes we don't recognize to home
    { path: '**', redirectTo: '', pathMatch: 'full' }
]
```

So your home page, in addition to the basic info it contains, might also contain some navigation (e.g., `<a routerLink="about">About Me</a>`). 

It doesn't need to be any more complex than that. A home page, an about page, and somewhere a button a user can click that will make an AJAX request to a node server and display the response.

**Comment by AndroidNextdoor** [comment]
Thanks Justin. I think I've been making this more difficult than it needs to be. Your clarification is greatly appreciated. I wanted to create an application that impresses, and wanted to make something a little more robust and got hung up in trying too much all at once. I'll revisit this evening when I have some more time.
Thanks again,
Andrew
