### ISSUE TITLE
Connection of MongoDB to Application

### ISSUE THREAD

**Issue by AndroidNextdoor** [AndroidNextdoor/myFirstAngularApp#2]
Having some issues getting the front end and back end to communicate.

Running a localhost MongoDB and I'm not getting any errors, it just hangs forever when trying to hit the end point localhost:3000/synap/nixdorfs...

Any idea what I might be doing wrong here?

Thanks,

Andrew

**Comment by mycompassspins** [comment]
So, I definitely applaud the effort, but this is kind of outside the scope of what I had in mind. You should keep at it, but not on account of our little project.

That said, here are a couple pointers:

First, you've got outdated mongoose and mongodb packages. `npm i --save mongoose@latest mongodb@latest`.

Second, no need to use the native MongoDb driver directly if you're using mongoose to connect to the db. 

```
mongoose.connect('mongodb://localhost:27017/synap_proj', { useNewUrlParser: true })
    .then((db) =>
    {
        console.log('MongoDb Connected');
    })
    .catch(e => console.log('Error connecting to db: ', e));
```

And in your api:

```
const mongoose = require('mongoose');
const NixDorf = mongoose.model('NixDorf', new mongoose.Schema({
    name: String,
    email: String
}));

router.get('/nixdorfs', function(req, res)
{
    NixDorf.find(function(err, nixdorfs)
    {
         if (err) return res.json({ success: false, message: err.message });
         return res.json({ success: true, nixdorfs });
    })
});
```

**Comment by AndroidNextdoor** [comment]
Thanks for those pointers Justin. I know I was attempting more than what was being asked for. I just wanted to try and make a good impression that I am willing to go above and beyond.

I appreciate all of your time and help.

-Andrew
